/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#003063',
        'on-primary-fixed-variant': '#00458d',
        error: '#ffb4ab',
        'tertiary-container': '#0077cc',
        'on-surface': '#e5e2e1',
        'on-primary-container': '#fdfbff',
        'on-error-container': '#ffdad6',
        'on-error': '#690005',
        'secondary-container': '#0062bf',
        'outline-variant': '#414753',
        'tertiary-fixed-dim': '#a1c9ff',
        outline: '#8b919f',
        'on-primary': '#002f64',
        'surface-container-low': '#1c1b1b',
        'inverse-primary': '#005db9',
        'tertiary-fixed': '#d2e4ff',
        'secondary-fixed-dim': '#a9c7ff',
        'surface-container': '#201f1f',
        'on-tertiary-fixed': '#001c37',
        'secondary-fixed': '#d6e3ff',
        'surface-bright': '#3a3939',
        'on-background': '#e5e2e1',
        primary: '#aac7ff',
        'on-primary-fixed': '#001b3e',
        surface: '#141313',
        'inverse-surface': '#e5e2e1',
        tertiary: '#a1c9ff',
        'surface-tint': '#aac7ff',
        'surface-container-high': '#2a2a2a',
        'primary-fixed-dim': '#aac7ff',
        'surface-variant': '#353434',
        'surface-container-lowest': '#0e0e0e',
        'error-container': '#93000a',
        'surface-dim': '#141313',
        'primary-fixed': '#d6e3ff',
        'on-secondary-fixed': '#001b3d',
        'on-tertiary-container': '#fdfcff',
        background: '#141313',
        'on-secondary-container': '#d2e1ff',
        'on-surface-variant': '#c1c6d6',
        'on-tertiary': '#00325a',
        'on-tertiary-fixed-variant': '#00487f',
        'inverse-on-surface': '#313030',
        'primary-container': '#0072e1',
        'on-secondary-fixed-variant': '#00468b',
        'surface-container-highest': '#353434',
        secondary: '#a9c7ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'container-max': '1440px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        unit: '4px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
        // New fonts for distinctive logo-like headings
        righteous: ['Righteous', 'cursive'],
        outfit: ['Outfit', 'sans-serif'],
        bebas: ['Bebas Neue', 'sans-serif'],
        grotesk: ['Space Grotesk', 'sans-serif'],
        playfair: ['Playfair Display', 'serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
      keyframes: {
        'marquee-left': {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'marquee-right': {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(0%)' },
        },
      },
      animation: {
        'marquee-left': 'marquee-left 30s linear infinite',
        'marquee-right': 'marquee-right 30s linear infinite',
      },
    },
  },
  plugins: [],
};